server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
#      - name: file-storage-service
#        url: /v3/api-docs/file-storage-service
#      - name: file-analysis-service
#        url: /v3/api-docs/file-analysis-service
      - name: file-storage-service
        url: /file-storage-service/v3/api-docs
      - name: file-analysis-service
        url: /file-analysis-service/v3/api-docs
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springdoc: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.web.reactive.DispatcherHandler: DEBUG
    org.springframework.web.server. российских: DEBUG